### ISSUE TITLE
Update ETC absolute zero point to more closely match GFA zero point

### ISSUE THREAD

**Issue by schlafly** [desihub/desietc#1]
The derived ETC transparencies are systematically offset from Aaron's GFA analysis by ~14%.  This leads to slower-than-appropriate survey speeds.  We should update the absolute zero point in order to compensate.  The y axis is mislabeled and should be (GFA transparency) / (ETC transparency).

![image](https://user-images.githubusercontent.com/1417841/131375553-58a934c1-a6b1-4f98-8f1b-ddf1b1e0fb4c.png)

**Comment by dkirkby** [comment]
I propose to recalibrate the ETC transparency with a small shift in the GFA zeropoint that I am using, from 27.06 to 26.92 where the shift -0.14 is calculated as `-2.5 log10(1.14)` rounded to 2 decimals.

The original zeropoint came from Aaron's analysis of standard stars measured in the GFAs under photometric conditions, but he used a different photometric system (PanSTARRS-r vs GAIA synthesized-r) and a slightly different flux measurement algorithm, so a small zeropoint shift to get consistency is not unexpected.

Any concerns with this approach @schlafly @ameisner?

**Comment by ameisner** [comment]
Sounds good to me. Thanks to both of you for looking into this...

**Comment by dkirkby** [comment]
Fixed in #6

**Comment by dkirkby** [comment]
Transparencies measured during the first night (20211007) with this change, showing some periods of sustained ~105%:
![image](https://user-images.githubusercontent.com/185007/136577707-5c5d7667-2da1-4642-9ebd-9928a4bb8d67.png)

@ameisner Can you check how well this new ETC normalization matches what you find offline?

**Comment by schlafly** [comment]
I'd note that in my plot there's ~5% scatter between the ETC and GFA, so that's not completely unexpected.

**Comment by ameisner** [comment]
Here's a plot showing the offline GFA transparency for 20211007:

![transp_20211007](https://user-images.githubusercontent.com/3253317/136648599-e36fe07b-3701-4734-bf4c-098a985c90fc.png)

The red line is 1.02, green is 1. The sustained period of transparency > 1 during the later part of the night was right about 1.02 or slightly less according to the offline pipeline.
