### ISSUE TITLE
No version string

### ISSUE THREAD

**Issue by weaverba137** [desihub/desietc#10]
Now that desietc is now part of the standard DESI release, it needs to be brought up to standard.  For starters, there is no version string:
```python
import desietc.__version__ as desietc_version
```
won't work.

**Comment by dkirkby** [comment]
Do you have a recommendation on how to do this @weaverba137?  None of the approaches listed [here](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) seems ideal.

**Comment by weaverba137** [comment]
I'm a little confused by your question.  We have many examples in the DESI software system.  Just cut and paste!

**Comment by weaverba137** [comment]
Rereading the initial report, I think I see the problem.  I should have said:

```python
import desietc.__version__ as desietc_version
```
*currently doesn't* work.  Not that it won't work.
