### ISSUE TITLE
Update effective time calibration

### ISSUE THREAD

**Issue by dkirkby** [desihub/desietc#11]
From @schlafly:
```
There has been a fluctuation in the value of EFFTIME_SPEC / EFFTIME_ETC such that we're now averaging something like 0.95.  We stayed at 1 between the two major shutdowns but have been at ~0.95 since then.
...
Let's go ahead and boost the amount of time we get given a particular requested time by 5%.
The goal is that exposure times after this tweak will be 5% longer than they otherwise would have been.
```

**Comment by dkirkby** [comment]
The simplest way to accomplish this is to adjust the default `scale` parameter of `accum.get_efftime` which is currently set to 1.11537 after #4.  Multiplying this by 1.05 gives 1.17114.

**Comment by schlafly** [comment]
@dkirkby , can you confirm the intended sign here?  We wanted to make exposures 5% longer.  We have been undercooking tiles since restart; if we applied this with the wrong sign that would go a long way to explaining the current issue.

**Comment by dkirkby** [comment]
Arrgh, I got this backwards and increased EFFTIME_ETC by 5%.

The correct scale value to use is 1.11537 * 0.95 = 1.05960.  I have fixed this in the code now and tagged 0.1.16.

**Comment by schlafly** [comment]
Thank you!  Any idea how the installation in the ICS environment works?  Do we need to wait for Klaus's return?  Especially challenging at the moment with the network down.

**Comment by schlafly** [comment]
Sorry, I see on Slack that you already resolved this; thanks!

**Comment by daqiii** [comment]
We just patched the file. As you know there is no access to external sites possible.
The next attempt is currently being made by Bob. If it works Ann will let you  (Eddie) know.

Klaus

From: Eddie Schlafly ***@***.***>
Date: Friday, August 11, 2023 at 1:34 PM
To: desihub/desietc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [desihub/desietc] Update effective time calibration (Issue #11)
Thank you! Any idea how the installation in the ICS environment works? Do we need to wait for Klaus's return? Especially challenging at the moment with the network down. — Reply to this email directly, view it on GitHub, or unsubscribe. You


Thank you! Any idea how the installation in the ICS environment works? Do we need to wait for Klaus's return? Especially challenging at the moment with the network down.
