### ISSUE TITLE
Update airmass scaling in nts_speed to be more steep

### ISSUE THREAD

**Issue by schlafly** [desihub/desietc#2]
Currently observed speeds are corrected to "zenith speeds" for use by the NTS by scaling them by the ratio of the transparency at zenith to the transparency at the observed airmass.  However, brighter skies and worse seeing also contribute to slower speeds off zenith, and indeed these seem to be the dominant effect in the r band.  We want to replace this with an X^1.75 scaling.
![image](https://user-images.githubusercontent.com/1417841/131376228-471065d2-9ce0-4eb0-997f-42c3560f6b32.png)

I've made the corresponding update to the SurveySpeed wiki here:
https://desi.lbl.gov/trac/wiki/SurveyOps/SurveySpeed

**Comment by dkirkby** [comment]
I have applied the same AIRCORRECTION=X**1.75 factor to all 6 speeds: (2-min, 20-min) x (dark, bright, backup).

**Comment by dkirkby** [comment]
Note that the ETC gets airmass from the MOUNTEL keyword associated with the acquisition image, so does not  track the changing airmass during a long exposure.  Also, the MOUNTEL keyword is not 100% reliable #3.

**Comment by dkirkby** [comment]
Fixed in #6
