### ISSUE TITLE
Update ETC calibration to EFFTIME_SPEC

### ISSUE THREAD

**Issue by schlafly** [desihub/desietc#4]
Looking at all maindark tiles observed so far, EFFTIME_SPEC / EFFTIME_ETC averages to something like 1.07.  It would be good to adjust the calibration so that we don't systematically overcook dark tiles.

![image](https://user-images.githubusercontent.com/1417841/134745769-f4848ae6-43f1-4ba7-b173-3ebb011b93e3.png)

**Comment by dkirkby** [comment]
Fixing #1 should increase EFFTIME_ETC by a factor `1.14**2` so I guess I need to recalibrate by `1.07 / 1.14**2 ~ 0.82` ?

**Comment by dkirkby** [comment]
We are now aiming for 1.06 (instead of 1.07) based on a @schlafly's latest comparison using all main survey dark tiles (20210514 - 20211005) and the new LRG_EFFTIME_DARK.

**Comment by dkirkby** [comment]
Fixed in #6
