### ISSUE TITLE
Do not apply dust corrections for backup program

### ISSUE THREAD

**Issue by dkirkby** [desihub/desietc#8]
The backup program target selection is not extinction corrected, so the ETC  effective time shouldn't be either.

Is any change needed for the backup speeds?

The ETC gets its dust extinction from the fiber-assign file associated with the current tile, calculated as the nanmedian of all targets with `OBJTYPE == "TGT"`.

All exposures use the same Ebv coefficient, which defaults to 2.165.

The ETC currently has no notion of the DARK / BRIGHT / BACKUP programs, beyond what is implied by the SBPROF = PSF / EGL / BGS / FLT, so the first issue is how to identify backup tiles.  Is there a program keyword somewhere in a fiberassign FITS header?

**Comment by araichoor** [comment]
The following keywords in the header of the 0th-extension of the fiberassign-TILEID.fits.gz files are BACKUP-specific:
```
FAPRGRM = 'backup  '
GOALTIME= 30. 
GOALTYPE= 'BACKUP  '
SBPROF  = 'PSF     '
```
Note that the `FAPRGRM` could be "hand-edited" when designing tiles for special tiles (so could be different than "BACKUP" for some non-main tiles, even if I m not sure why we d do that).
So using `GOALTYPE=="BACKUP"` to identify BACKUP tiles should be fine.

An alternative way would be to use `SBPROF=="PSF"`, as only BACKUP tiles should have this setting: https://github.com/desihub/fiberassign/blob/ac6e935614cad8c888f2bd5b93000eb955185292/bin/fba_launch#L51-L57.
But I find it less explicit - and maybe more fragile? - than using `GOALTYPE`.

**Comment by schlafly** [comment]
I'd vote for pulling this from FAPRGRM in the fiberassign header.  I don't think you use source count noise for anything, but ideally we'd like that to be much higher for BACKUP.  That would be a more significant change that we would fold into the bright and dark programs as well.

**Comment by schlafly** [comment]
@dkirkby , goal is to start the backup in the next week.  Any chance of getting this in?
